### PR TITLE
Install necessary plugins for dump-powervs.sh

### PR DESCRIPTION
**Pull request by mjturek**
Currently the post-run `dump-powervs.sh` step is failing with 'dl' is not a registered command. Check your list of installed plug-ins. See 'ibmcloud help'. This should add the necessary plugins.

### CODE REVIEW

**Comment by hamzy** [comment]
I would suggest doing similar to this https://github.com/openshift/release/blob/master/ci-operator/step-registry/ipi/install/powervs/install/ipi-install-powervs-install-commands.sh#L219-L256
As that is what the real CI does.

**Review by Shilpi-Das1 — CHANGES_REQUESTED** [review]
@mjturek You need to install these plugins` infrastructure-service  cloud-internet-services  dl-cli dns` as power-iaas and cloud-object-storage are already installed or use flag -f for force installation otherwise it will fail. The other plugins are installed in our jenkins image. In future we will add these plugins in our image

https://github.com/ppc64le-cloud/jenkins-infra/blob/master/images/jenkins-inbound-agent/Dockerfile

**Comment by Shilpi-Das1** [comment]
Created another PR with addressing comments
https://github.com/ppc64le-cloud/jenkins-infra/pull/213
This PR can be closed

**Comment by sudeeshjohn** [comment]
https://github.com/ppc64le-cloud/jenkins-infra/pull/213 merged, closing this RP

**Pull request closed without merging**
