### PR TITLE
Fixing capture artifacts and kube config failures

### PR DESCRIPTION
**Pull request by Shilpi-Das1**

### CODE REVIEW

**Comment by mkumatag** [comment]
@sudeeshjohn its working fine now, please add OWNERS file as well, e.g: https://github.com/ppc64le-cloud/test-infra/blob/master/OWNERS

**Comment by mkumatag** [comment]
https://github.com/ppc64le-cloud/test-infra/pull/194 already merged, not sure why it is not triggering the test here!

**Comment by mkumatag** [comment]
@Shilpi-Das1 can you please close this PR and open a fresh one and see if it really triggering the test or not?

**Comment by Shilpi-Das1** [comment]
Closing this PR

**Comment by Shilpi-Das1** [comment]
Opened new PR https://github.com/ppc64le-cloud/jenkins-infra/pull/29

**Pull request closed without merging**
