### PR TITLE
Change upgrade related environment vars

### PR DESCRIPTION
**Pull request by Neha-dot-Yadav**
This PR -
1. Adds upgrade pause and delay variable default values.
2. Removes vars from powervc and powervs terraform templates.
Signed-off-by: Neha Yadav <neha.yadav3@ibm.com>

### CODE REVIEW

**Review by Shilpi-Das1 — COMMENTED** [review]
@Neha-dot-Yadav Please change https://github.com/ppc64le-cloud/jenkins-infra/blob/21d62229e828a97476fbb267cbc38a16538c7c23/jobs/pipelines/powervm/ocp/4.11/daily-ocp4.11-to-4.12-powervm-p8-min-upgrade/Jenkinsfile#L70 this line to latest-${OCP_RELEASE}-stable-build.txt Change it all over jenkins file

**Comment by Neha-dot-Yadav** [comment]
@Shilpi-Das1 updated with suggested changes

**Review by Shilpi-Das1 — COMMENTED** [review]
@Neha-dot-Yadav getArtifacts("mirror-openshift-release", "latest-${OCP_RELEASE}-stable-build.txt") This was just for upgrade jobs not all jobs

**Comment by Neha-dot-Yadav** [comment]
@Shilpi-Das1 added the suggested changes.

**Review by Shilpi-Das1 — APPROVED** [review]
/lgtm

**Review by Shilpi-Das1 — APPROVED** [review]
/lgtm

**Pull request merged**
